//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CardLanguage.g4 by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CardLanguageParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public interface ICardLanguageListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBody([NotNull] CardLanguageParser.BodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBody([NotNull] CardLanguageParser.BodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.childNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChildNode([NotNull] CardLanguageParser.ChildNodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.childNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChildNode([NotNull] CardLanguageParser.ChildNodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.open"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpen([NotNull] CardLanguageParser.OpenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.open"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpen([NotNull] CardLanguageParser.OpenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.many"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMany([NotNull] CardLanguageParser.ManyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.many"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMany([NotNull] CardLanguageParser.ManyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.close"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClose([NotNull] CardLanguageParser.CloseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.close"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClose([NotNull] CardLanguageParser.CloseContext context);
}
