//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CardLanguage.g4 by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICardLanguageListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public partial class CardLanguageBaseListener : ICardLanguageListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.gameaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGameaction([NotNull] CardLanguageParser.GameactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.gameaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGameaction([NotNull] CardLanguageParser.GameactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAction([NotNull] CardLanguageParser.ActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAction([NotNull] CardLanguageParser.ActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.setaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetaction([NotNull] CardLanguageParser.SetactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.setaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetaction([NotNull] CardLanguageParser.SetactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.moveaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoveaction([NotNull] CardLanguageParser.MoveactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.moveaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoveaction([NotNull] CardLanguageParser.MoveactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.card"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCard([NotNull] CardLanguageParser.CardContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.card"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCard([NotNull] CardLanguageParser.CardContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.rawstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRawstorage([NotNull] CardLanguageParser.RawstorageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.rawstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRawstorage([NotNull] CardLanguageParser.RawstorageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.locstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocstorage([NotNull] CardLanguageParser.LocstorageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.locstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocstorage([NotNull] CardLanguageParser.LocstorageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] CardLanguageParser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] CardLanguageParser.NameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.quantifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuantifier([NotNull] CardLanguageParser.QuantifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.quantifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuantifier([NotNull] CardLanguageParser.QuantifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean([NotNull] CardLanguageParser.BooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean([NotNull] CardLanguageParser.BooleanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.intOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntOp([NotNull] CardLanguageParser.IntOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.intOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntOp([NotNull] CardLanguageParser.IntOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.@int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt([NotNull] CardLanguageParser.IntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.@int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt([NotNull] CardLanguageParser.IntContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
