//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CardLanguage.g4 by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICardLanguageListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public partial class CardLanguageBaseListener : ICardLanguageListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBody([NotNull] CardLanguageParser.BodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBody([NotNull] CardLanguageParser.BodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.childNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChildNode([NotNull] CardLanguageParser.ChildNodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.childNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChildNode([NotNull] CardLanguageParser.ChildNodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.open"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpen([NotNull] CardLanguageParser.OpenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.open"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpen([NotNull] CardLanguageParser.OpenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.many"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMany([NotNull] CardLanguageParser.ManyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.many"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMany([NotNull] CardLanguageParser.ManyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.close"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClose([NotNull] CardLanguageParser.CloseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.close"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClose([NotNull] CardLanguageParser.CloseContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
