//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CardLanguage.g4 by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICardLanguageListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public partial class CardLanguageBaseListener : ICardLanguageListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.stage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStage([NotNull] CardLanguageParser.StageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.stage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStage([NotNull] CardLanguageParser.StageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.endcondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndcondition([NotNull] CardLanguageParser.EndconditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.endcondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndcondition([NotNull] CardLanguageParser.EndconditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.computermoves"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComputermoves([NotNull] CardLanguageParser.ComputermovesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.computermoves"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComputermoves([NotNull] CardLanguageParser.ComputermovesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.playermoves"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlayermoves([NotNull] CardLanguageParser.PlayermovesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.playermoves"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlayermoves([NotNull] CardLanguageParser.PlayermovesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.multigameaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultigameaction([NotNull] CardLanguageParser.MultigameactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.multigameaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultigameaction([NotNull] CardLanguageParser.MultigameactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.gameaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGameaction([NotNull] CardLanguageParser.GameactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.gameaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGameaction([NotNull] CardLanguageParser.GameactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.multiaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiaction([NotNull] CardLanguageParser.MultiactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.multiaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiaction([NotNull] CardLanguageParser.MultiactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAction([NotNull] CardLanguageParser.ActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAction([NotNull] CardLanguageParser.ActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.loccreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoccreate([NotNull] CardLanguageParser.LoccreateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.loccreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoccreate([NotNull] CardLanguageParser.LoccreateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.locationdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocationdef([NotNull] CardLanguageParser.LocationdefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.locationdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocationdef([NotNull] CardLanguageParser.LocationdefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.storagecreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStoragecreate([NotNull] CardLanguageParser.StoragecreateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.storagecreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStoragecreate([NotNull] CardLanguageParser.StoragecreateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.playercreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlayercreate([NotNull] CardLanguageParser.PlayercreateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.playercreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlayercreate([NotNull] CardLanguageParser.PlayercreateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.teamcreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTeamcreate([NotNull] CardLanguageParser.TeamcreateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.teamcreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTeamcreate([NotNull] CardLanguageParser.TeamcreateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.obj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObj([NotNull] CardLanguageParser.ObjContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.obj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObj([NotNull] CardLanguageParser.ObjContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.init"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInit([NotNull] CardLanguageParser.InitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.init"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInit([NotNull] CardLanguageParser.InitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.playerinit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlayerinit([NotNull] CardLanguageParser.PlayerinitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.playerinit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlayerinit([NotNull] CardLanguageParser.PlayerinitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.deckinit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeckinit([NotNull] CardLanguageParser.DeckinitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.deckinit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeckinit([NotNull] CardLanguageParser.DeckinitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.deck"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeck([NotNull] CardLanguageParser.DeckContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.deck"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeck([NotNull] CardLanguageParser.DeckContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute([NotNull] CardLanguageParser.AttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute([NotNull] CardLanguageParser.AttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.pointsinit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointsinit([NotNull] CardLanguageParser.PointsinitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.pointsinit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointsinit([NotNull] CardLanguageParser.PointsinitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.awards"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAwards([NotNull] CardLanguageParser.AwardsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.awards"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAwards([NotNull] CardLanguageParser.AwardsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.setaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetaction([NotNull] CardLanguageParser.SetactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.setaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetaction([NotNull] CardLanguageParser.SetactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.incaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncaction([NotNull] CardLanguageParser.IncactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.incaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncaction([NotNull] CardLanguageParser.IncactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.decaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecaction([NotNull] CardLanguageParser.DecactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.decaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecaction([NotNull] CardLanguageParser.DecactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.moveaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoveaction([NotNull] CardLanguageParser.MoveactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.moveaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoveaction([NotNull] CardLanguageParser.MoveactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.copyaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCopyaction([NotNull] CardLanguageParser.CopyactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.copyaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCopyaction([NotNull] CardLanguageParser.CopyactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.turnaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTurnaction([NotNull] CardLanguageParser.TurnactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.turnaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTurnaction([NotNull] CardLanguageParser.TurnactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.removeaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRemoveaction([NotNull] CardLanguageParser.RemoveactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.removeaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRemoveaction([NotNull] CardLanguageParser.RemoveactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.shuffleaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShuffleaction([NotNull] CardLanguageParser.ShuffleactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.shuffleaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShuffleaction([NotNull] CardLanguageParser.ShuffleactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.namelist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamelist([NotNull] CardLanguageParser.NamelistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.namelist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamelist([NotNull] CardLanguageParser.NamelistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.loclist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoclist([NotNull] CardLanguageParser.LoclistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.loclist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoclist([NotNull] CardLanguageParser.LoclistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.loc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoc([NotNull] CardLanguageParser.LocContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.loc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoc([NotNull] CardLanguageParser.LocContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.imag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImag([NotNull] CardLanguageParser.ImagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.imag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImag([NotNull] CardLanguageParser.ImagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.card"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCard([NotNull] CardLanguageParser.CardContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.card"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCard([NotNull] CardLanguageParser.CardContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.owner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOwner([NotNull] CardLanguageParser.OwnerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.owner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOwner([NotNull] CardLanguageParser.OwnerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.rawstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRawstorage([NotNull] CardLanguageParser.RawstorageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.rawstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRawstorage([NotNull] CardLanguageParser.RawstorageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.locstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocstorage([NotNull] CardLanguageParser.LocstorageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.locstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocstorage([NotNull] CardLanguageParser.LocstorageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.who"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWho([NotNull] CardLanguageParser.WhoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.who"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWho([NotNull] CardLanguageParser.WhoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.who2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWho2([NotNull] CardLanguageParser.Who2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.who2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWho2([NotNull] CardLanguageParser.Who2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.trueany"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrueany([NotNull] CardLanguageParser.TrueanyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.trueany"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrueany([NotNull] CardLanguageParser.TrueanyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.whereclause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhereclause([NotNull] CardLanguageParser.WhereclauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.whereclause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhereclause([NotNull] CardLanguageParser.WhereclauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.boolatt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolatt([NotNull] CardLanguageParser.BoolattContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.boolatt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolatt([NotNull] CardLanguageParser.BoolattContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.attrcomp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttrcomp([NotNull] CardLanguageParser.AttrcompContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.attrcomp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttrcomp([NotNull] CardLanguageParser.AttrcompContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.cardatt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCardatt([NotNull] CardLanguageParser.CardattContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.cardatt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCardatt([NotNull] CardLanguageParser.CardattContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.posq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPosq([NotNull] CardLanguageParser.PosqContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.posq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPosq([NotNull] CardLanguageParser.PosqContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean([NotNull] CardLanguageParser.BooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean([NotNull] CardLanguageParser.BooleanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.intop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntop([NotNull] CardLanguageParser.IntopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.intop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntop([NotNull] CardLanguageParser.IntopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.mult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMult([NotNull] CardLanguageParser.MultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.mult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMult([NotNull] CardLanguageParser.MultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.subtract"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubtract([NotNull] CardLanguageParser.SubtractContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.subtract"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubtract([NotNull] CardLanguageParser.SubtractContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.mod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMod([NotNull] CardLanguageParser.ModContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.mod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMod([NotNull] CardLanguageParser.ModContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.divide"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDivide([NotNull] CardLanguageParser.DivideContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.divide"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDivide([NotNull] CardLanguageParser.DivideContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.@sizeof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSizeof([NotNull] CardLanguageParser.SizeofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.@sizeof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSizeof([NotNull] CardLanguageParser.SizeofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.maxof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMaxof([NotNull] CardLanguageParser.MaxofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.maxof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMaxof([NotNull] CardLanguageParser.MaxofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.unionof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnionof([NotNull] CardLanguageParser.UnionofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.unionof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnionof([NotNull] CardLanguageParser.UnionofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.sum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSum([NotNull] CardLanguageParser.SumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.sum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSum([NotNull] CardLanguageParser.SumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.@int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt([NotNull] CardLanguageParser.IntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.@int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt([NotNull] CardLanguageParser.IntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.namegr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamegr([NotNull] CardLanguageParser.NamegrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.namegr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamegr([NotNull] CardLanguageParser.NamegrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CardLanguageParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] CardLanguageParser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CardLanguageParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] CardLanguageParser.NameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
