//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Recycle.g4 by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IRecycleListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public partial class RecycleBaseListener : IRecycleListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.game"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGame([NotNull] RecycleParser.GameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.game"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGame([NotNull] RecycleParser.GameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.setup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetup([NotNull] RecycleParser.SetupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.setup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetup([NotNull] RecycleParser.SetupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.stage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStage([NotNull] RecycleParser.StageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.stage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStage([NotNull] RecycleParser.StageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.scoring"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScoring([NotNull] RecycleParser.ScoringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.scoring"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScoring([NotNull] RecycleParser.ScoringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.endcondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndcondition([NotNull] RecycleParser.EndconditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.endcondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndcondition([NotNull] RecycleParser.EndconditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.computermoves"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComputermoves([NotNull] RecycleParser.ComputermovesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.computermoves"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComputermoves([NotNull] RecycleParser.ComputermovesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.playermoves"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlayermoves([NotNull] RecycleParser.PlayermovesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.playermoves"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlayermoves([NotNull] RecycleParser.PlayermovesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.multigameaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultigameaction([NotNull] RecycleParser.MultigameactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.multigameaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultigameaction([NotNull] RecycleParser.MultigameactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.gameaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGameaction([NotNull] RecycleParser.GameactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.gameaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGameaction([NotNull] RecycleParser.GameactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.multiaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiaction([NotNull] RecycleParser.MultiactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.multiaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiaction([NotNull] RecycleParser.MultiactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAction([NotNull] RecycleParser.ActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAction([NotNull] RecycleParser.ActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.playercreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlayercreate([NotNull] RecycleParser.PlayercreateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.playercreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlayercreate([NotNull] RecycleParser.PlayercreateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.teamcreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTeamcreate([NotNull] RecycleParser.TeamcreateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.teamcreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTeamcreate([NotNull] RecycleParser.TeamcreateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.deckcreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeckcreate([NotNull] RecycleParser.DeckcreateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.deckcreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeckcreate([NotNull] RecycleParser.DeckcreateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.deck"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeck([NotNull] RecycleParser.DeckContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.deck"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeck([NotNull] RecycleParser.DeckContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute([NotNull] RecycleParser.AttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute([NotNull] RecycleParser.AttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.initpoints"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitpoints([NotNull] RecycleParser.InitpointsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.initpoints"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitpoints([NotNull] RecycleParser.InitpointsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.awards"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAwards([NotNull] RecycleParser.AwardsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.awards"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAwards([NotNull] RecycleParser.AwardsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.subaward"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubaward([NotNull] RecycleParser.SubawardContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.subaward"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubaward([NotNull] RecycleParser.SubawardContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.cycleaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCycleaction([NotNull] RecycleParser.CycleactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.cycleaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCycleaction([NotNull] RecycleParser.CycleactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.setaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetaction([NotNull] RecycleParser.SetactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.setaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetaction([NotNull] RecycleParser.SetactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.incaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncaction([NotNull] RecycleParser.IncactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.incaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncaction([NotNull] RecycleParser.IncactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.decaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecaction([NotNull] RecycleParser.DecactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.decaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecaction([NotNull] RecycleParser.DecactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.moveaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoveaction([NotNull] RecycleParser.MoveactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.moveaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoveaction([NotNull] RecycleParser.MoveactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.copyaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCopyaction([NotNull] RecycleParser.CopyactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.copyaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCopyaction([NotNull] RecycleParser.CopyactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.removeaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRemoveaction([NotNull] RecycleParser.RemoveactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.removeaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRemoveaction([NotNull] RecycleParser.RemoveactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.shuffleaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShuffleaction([NotNull] RecycleParser.ShuffleactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.shuffleaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShuffleaction([NotNull] RecycleParser.ShuffleactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.turnaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTurnaction([NotNull] RecycleParser.TurnactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.turnaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTurnaction([NotNull] RecycleParser.TurnactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.card"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCard([NotNull] RecycleParser.CardContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.card"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCard([NotNull] RecycleParser.CardContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.cardp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCardp([NotNull] RecycleParser.CardpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.cardp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCardp([NotNull] RecycleParser.CardpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.cardm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCardm([NotNull] RecycleParser.CardmContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.cardm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCardm([NotNull] RecycleParser.CardmContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.owner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOwner([NotNull] RecycleParser.OwnerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.owner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOwner([NotNull] RecycleParser.OwnerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.rawstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRawstorage([NotNull] RecycleParser.RawstorageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.rawstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRawstorage([NotNull] RecycleParser.RawstorageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.cstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCstorage([NotNull] RecycleParser.CstorageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.cstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCstorage([NotNull] RecycleParser.CstorageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.locstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocstorage([NotNull] RecycleParser.LocstorageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.locstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocstorage([NotNull] RecycleParser.LocstorageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.memstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemstorage([NotNull] RecycleParser.MemstorageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.memstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemstorage([NotNull] RecycleParser.MemstorageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.who"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWho([NotNull] RecycleParser.WhoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.who"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWho([NotNull] RecycleParser.WhoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.who2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWho2([NotNull] RecycleParser.Who2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.who2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWho2([NotNull] RecycleParser.Who2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.trueany"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrueany([NotNull] RecycleParser.TrueanyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.trueany"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrueany([NotNull] RecycleParser.TrueanyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.whereclause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhereclause([NotNull] RecycleParser.WhereclauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.whereclause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhereclause([NotNull] RecycleParser.WhereclauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.boolatt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolatt([NotNull] RecycleParser.BoolattContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.boolatt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolatt([NotNull] RecycleParser.BoolattContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.attrcomp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttrcomp([NotNull] RecycleParser.AttrcompContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.attrcomp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttrcomp([NotNull] RecycleParser.AttrcompContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.cardatt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCardatt([NotNull] RecycleParser.CardattContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.cardatt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCardatt([NotNull] RecycleParser.CardattContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.posq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPosq([NotNull] RecycleParser.PosqContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.posq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPosq([NotNull] RecycleParser.PosqContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean([NotNull] RecycleParser.BooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean([NotNull] RecycleParser.BooleanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.intop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntop([NotNull] RecycleParser.IntopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.intop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntop([NotNull] RecycleParser.IntopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.add"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd([NotNull] RecycleParser.AddContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.add"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd([NotNull] RecycleParser.AddContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.mult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMult([NotNull] RecycleParser.MultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.mult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMult([NotNull] RecycleParser.MultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.subtract"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubtract([NotNull] RecycleParser.SubtractContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.subtract"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubtract([NotNull] RecycleParser.SubtractContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.mod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMod([NotNull] RecycleParser.ModContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.mod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMod([NotNull] RecycleParser.ModContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.divide"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDivide([NotNull] RecycleParser.DivideContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.divide"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDivide([NotNull] RecycleParser.DivideContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.@sizeof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSizeof([NotNull] RecycleParser.SizeofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.@sizeof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSizeof([NotNull] RecycleParser.SizeofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.maxof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMaxof([NotNull] RecycleParser.MaxofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.maxof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMaxof([NotNull] RecycleParser.MaxofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.unionof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnionof([NotNull] RecycleParser.UnionofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.unionof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnionof([NotNull] RecycleParser.UnionofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.sum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSum([NotNull] RecycleParser.SumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.sum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSum([NotNull] RecycleParser.SumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.@int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt([NotNull] RecycleParser.IntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.@int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt([NotNull] RecycleParser.IntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.namegr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamegr([NotNull] RecycleParser.NamegrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.namegr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamegr([NotNull] RecycleParser.NamegrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] RecycleParser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] RecycleParser.NameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
