//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/markgoadrich/Github/cardstock/CardStock/Recycle.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IRecycleListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class RecycleBaseListener : IRecycleListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar([NotNull] RecycleParser.VarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar([NotNull] RecycleParser.VarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.vars"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVars([NotNull] RecycleParser.VarsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.vars"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVars([NotNull] RecycleParser.VarsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.varo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVaro([NotNull] RecycleParser.VaroContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.varo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVaro([NotNull] RecycleParser.VaroContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.varp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarp([NotNull] RecycleParser.VarpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.varp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarp([NotNull] RecycleParser.VarpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.vari"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVari([NotNull] RecycleParser.VariContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.vari"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVari([NotNull] RecycleParser.VariContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.varb"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarb([NotNull] RecycleParser.VarbContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.varb"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarb([NotNull] RecycleParser.VarbContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.varc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarc([NotNull] RecycleParser.VarcContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.varc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarc([NotNull] RecycleParser.VarcContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.varcs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarcs([NotNull] RecycleParser.VarcsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.varcs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarcs([NotNull] RecycleParser.VarcsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.varcard"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarcard([NotNull] RecycleParser.VarcardContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.varcard"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarcard([NotNull] RecycleParser.VarcardContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.game"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGame([NotNull] RecycleParser.GameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.game"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGame([NotNull] RecycleParser.GameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.declare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclare([NotNull] RecycleParser.DeclareContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.declare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclare([NotNull] RecycleParser.DeclareContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.setup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetup([NotNull] RecycleParser.SetupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.setup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetup([NotNull] RecycleParser.SetupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.scoring"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScoring([NotNull] RecycleParser.ScoringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.scoring"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScoring([NotNull] RecycleParser.ScoringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.stage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStage([NotNull] RecycleParser.StageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.stage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStage([NotNull] RecycleParser.StageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.endcondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndcondition([NotNull] RecycleParser.EndconditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.endcondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndcondition([NotNull] RecycleParser.EndconditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.multiaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiaction([NotNull] RecycleParser.MultiactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.multiaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiaction([NotNull] RecycleParser.MultiactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.multiaction2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiaction2([NotNull] RecycleParser.Multiaction2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.multiaction2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiaction2([NotNull] RecycleParser.Multiaction2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.condact"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondact([NotNull] RecycleParser.CondactContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.condact"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondact([NotNull] RecycleParser.CondactContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.agg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAgg([NotNull] RecycleParser.AggContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.agg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAgg([NotNull] RecycleParser.AggContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.let"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLet([NotNull] RecycleParser.LetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.let"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLet([NotNull] RecycleParser.LetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAction([NotNull] RecycleParser.ActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAction([NotNull] RecycleParser.ActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.playercreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlayercreate([NotNull] RecycleParser.PlayercreateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.playercreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlayercreate([NotNull] RecycleParser.PlayercreateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.teamcreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTeamcreate([NotNull] RecycleParser.TeamcreateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.teamcreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTeamcreate([NotNull] RecycleParser.TeamcreateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.teams"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTeams([NotNull] RecycleParser.TeamsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.teams"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTeams([NotNull] RecycleParser.TeamsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.deckcreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeckcreate([NotNull] RecycleParser.DeckcreateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.deckcreate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeckcreate([NotNull] RecycleParser.DeckcreateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.deck"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeck([NotNull] RecycleParser.DeckContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.deck"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeck([NotNull] RecycleParser.DeckContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute([NotNull] RecycleParser.AttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute([NotNull] RecycleParser.AttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.initpoints"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitpoints([NotNull] RecycleParser.InitpointsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.initpoints"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitpoints([NotNull] RecycleParser.InitpointsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.awards"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAwards([NotNull] RecycleParser.AwardsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.awards"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAwards([NotNull] RecycleParser.AwardsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.subaward"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubaward([NotNull] RecycleParser.SubawardContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.subaward"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubaward([NotNull] RecycleParser.SubawardContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.cycleaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCycleaction([NotNull] RecycleParser.CycleactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.cycleaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCycleaction([NotNull] RecycleParser.CycleactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.setaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetaction([NotNull] RecycleParser.SetactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.setaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetaction([NotNull] RecycleParser.SetactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.setstraction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetstraction([NotNull] RecycleParser.SetstractionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.setstraction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetstraction([NotNull] RecycleParser.SetstractionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.incaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncaction([NotNull] RecycleParser.IncactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.incaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncaction([NotNull] RecycleParser.IncactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.decaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecaction([NotNull] RecycleParser.DecactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.decaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecaction([NotNull] RecycleParser.DecactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.moveaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoveaction([NotNull] RecycleParser.MoveactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.moveaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoveaction([NotNull] RecycleParser.MoveactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.shuffleaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShuffleaction([NotNull] RecycleParser.ShuffleactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.shuffleaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShuffleaction([NotNull] RecycleParser.ShuffleactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.turnaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTurnaction([NotNull] RecycleParser.TurnactionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.turnaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTurnaction([NotNull] RecycleParser.TurnactionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.repeat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeat([NotNull] RecycleParser.RepeatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.repeat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeat([NotNull] RecycleParser.RepeatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.pointstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointstorage([NotNull] RecycleParser.PointstorageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.pointstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointstorage([NotNull] RecycleParser.PointstorageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.card"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCard([NotNull] RecycleParser.CardContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.card"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCard([NotNull] RecycleParser.CardContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.actual"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActual([NotNull] RecycleParser.ActualContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.actual"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActual([NotNull] RecycleParser.ActualContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.maxof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMaxof([NotNull] RecycleParser.MaxofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.maxof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMaxof([NotNull] RecycleParser.MaxofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.minof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMinof([NotNull] RecycleParser.MinofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.minof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMinof([NotNull] RecycleParser.MinofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.locpre"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocpre([NotNull] RecycleParser.LocpreContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.locpre"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocpre([NotNull] RecycleParser.LocpreContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.locdesc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocdesc([NotNull] RecycleParser.LocdescContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.locdesc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocdesc([NotNull] RecycleParser.LocdescContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.who"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWho([NotNull] RecycleParser.WhoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.who"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWho([NotNull] RecycleParser.WhoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.whop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhop([NotNull] RecycleParser.WhopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.whop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhop([NotNull] RecycleParser.WhopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.whot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhot([NotNull] RecycleParser.WhotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.whot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhot([NotNull] RecycleParser.WhotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.whodesc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhodesc([NotNull] RecycleParser.WhodescContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.whodesc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhodesc([NotNull] RecycleParser.WhodescContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.owner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOwner([NotNull] RecycleParser.OwnerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.owner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOwner([NotNull] RecycleParser.OwnerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.teamp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTeamp([NotNull] RecycleParser.TeampContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.teamp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTeamp([NotNull] RecycleParser.TeampContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.typed"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTyped([NotNull] RecycleParser.TypedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.typed"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTyped([NotNull] RecycleParser.TypedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.collection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCollection([NotNull] RecycleParser.CollectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.collection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCollection([NotNull] RecycleParser.CollectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.strcollection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStrcollection([NotNull] RecycleParser.StrcollectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.strcollection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStrcollection([NotNull] RecycleParser.StrcollectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange([NotNull] RecycleParser.RangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange([NotNull] RecycleParser.RangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.other"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOther([NotNull] RecycleParser.OtherContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.other"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOther([NotNull] RecycleParser.OtherContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.cstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCstorage([NotNull] RecycleParser.CstorageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.cstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCstorage([NotNull] RecycleParser.CstorageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.sortof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSortof([NotNull] RecycleParser.SortofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.sortof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSortof([NotNull] RecycleParser.SortofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.unionof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnionof([NotNull] RecycleParser.UnionofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.unionof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnionof([NotNull] RecycleParser.UnionofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.intersectof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntersectof([NotNull] RecycleParser.IntersectofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.intersectof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntersectof([NotNull] RecycleParser.IntersectofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.disjunctionof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDisjunctionof([NotNull] RecycleParser.DisjunctionofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.disjunctionof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDisjunctionof([NotNull] RecycleParser.DisjunctionofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.filter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilter([NotNull] RecycleParser.FilterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.filter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilter([NotNull] RecycleParser.FilterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.memstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemstorage([NotNull] RecycleParser.MemstorageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.memstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemstorage([NotNull] RecycleParser.MemstorageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.cstoragecollection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCstoragecollection([NotNull] RecycleParser.CstoragecollectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.cstoragecollection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCstoragecollection([NotNull] RecycleParser.CstoragecollectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.memset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemset([NotNull] RecycleParser.MemsetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.memset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemset([NotNull] RecycleParser.MemsetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.run"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRun([NotNull] RecycleParser.RunContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.run"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRun([NotNull] RecycleParser.RunContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.subset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubset([NotNull] RecycleParser.SubsetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.subset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubset([NotNull] RecycleParser.SubsetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.tuple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTuple([NotNull] RecycleParser.TupleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.tuple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTuple([NotNull] RecycleParser.TupleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.partition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPartition([NotNull] RecycleParser.PartitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.partition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPartition([NotNull] RecycleParser.PartitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.aggcs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggcs([NotNull] RecycleParser.AggcsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.aggcs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggcs([NotNull] RecycleParser.AggcsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean([NotNull] RecycleParser.BooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean([NotNull] RecycleParser.BooleanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.intop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntop([NotNull] RecycleParser.IntopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.intop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntop([NotNull] RecycleParser.IntopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.aggb"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggb([NotNull] RecycleParser.AggbContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.aggb"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggb([NotNull] RecycleParser.AggbContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt([NotNull] RecycleParser.IntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt([NotNull] RecycleParser.IntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.sum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSum([NotNull] RecycleParser.SumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.sum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSum([NotNull] RecycleParser.SumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.score"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScore([NotNull] RecycleParser.ScoreContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.score"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScore([NotNull] RecycleParser.ScoreContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.add"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd([NotNull] RecycleParser.AddContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.add"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd([NotNull] RecycleParser.AddContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.mult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMult([NotNull] RecycleParser.MultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.mult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMult([NotNull] RecycleParser.MultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.subtract"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubtract([NotNull] RecycleParser.SubtractContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.subtract"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubtract([NotNull] RecycleParser.SubtractContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.mod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMod([NotNull] RecycleParser.ModContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.mod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMod([NotNull] RecycleParser.ModContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.divide"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDivide([NotNull] RecycleParser.DivideContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.divide"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDivide([NotNull] RecycleParser.DivideContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.exponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExponent([NotNull] RecycleParser.ExponentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.exponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExponent([NotNull] RecycleParser.ExponentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.triangular"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTriangular([NotNull] RecycleParser.TriangularContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.triangular"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTriangular([NotNull] RecycleParser.TriangularContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.fibonacci"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFibonacci([NotNull] RecycleParser.FibonacciContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.fibonacci"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFibonacci([NotNull] RecycleParser.FibonacciContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.random"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRandom([NotNull] RecycleParser.RandomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.random"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRandom([NotNull] RecycleParser.RandomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.sizeof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSizeof([NotNull] RecycleParser.SizeofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.sizeof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSizeof([NotNull] RecycleParser.SizeofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.aggi"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggi([NotNull] RecycleParser.AggiContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.aggi"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggi([NotNull] RecycleParser.AggiContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.rawstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRawstorage([NotNull] RecycleParser.RawstorageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.rawstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRawstorage([NotNull] RecycleParser.RawstorageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.str"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStr([NotNull] RecycleParser.StrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.str"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStr([NotNull] RecycleParser.StrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.strstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStrstorage([NotNull] RecycleParser.StrstorageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.strstorage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStrstorage([NotNull] RecycleParser.StrstorageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.cardatt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCardatt([NotNull] RecycleParser.CardattContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.cardatt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCardatt([NotNull] RecycleParser.CardattContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RecycleParser.namegr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamegr([NotNull] RecycleParser.NamegrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RecycleParser.namegr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamegr([NotNull] RecycleParser.NamegrContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
