﻿using System;
using System.Diagnostics;
using System.IO;

namespace CardGames
{
    public class PythonController
    {
        public PythonController()
        {
         

        }

		public void run_cmd()
		{
            ProcessStartInfo pythonInfo = new ProcessStartInfo();
			pythonInfo.FileName = "/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5";
            pythonInfo.Arguments = "/Users/anna/PycharmProjects/basic_generator/Game_Generator/gen_3.0.py";
            pythonInfo.CreateNoWindow = false; // We don't need new window
            //pythonInfo.RedirectStandardOutput = false;// Any output, generated by application will be redirected back
            //pythonInfo.RedirectStandardError = false; // Any error in standard output will be redirected back (for example exceptions)

            pythonInfo.UseShellExecute = true;

			Console.WriteLine("Python Starting");
            Process process = Process.Start(pythonInfo);
            process.WaitForExit();
            process.Close();
			

		}
    }
}
